name: AI Failure check

on:
  workflow_run:
    workflows: "Test and Deploy"
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: success
        run: |
          echo "trigger build workflow success"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      actions: read
      contents: read
      models: read
    steps:
      - name: failure
        run: |
          echo "trigger build workflow failed"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get error info
        id: get-error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ワークフローの実行IDを取得
          RUN_ID=${{ github.event.workflow_run.id }}
          echo "RUN_ID: $RUN_ID"
          # ワークフロー情報を環境変数に保存
          echo "WORKFLOW_NAME=${{ github.event.workflow_run.name }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV

          # ジョブの一覧を取得
          JOBS=$(gh api repos/${{ github.repository }}/actions/runs/${RUN_ID}/jobs --jq '.jobs')

          # 失敗したジョブのログを取得
          echo "FAILED_LOGS<<EOF" >> $GITHUB_ENV

          for job in $(echo "$JOBS" | jq -r '.[] | select(.conclusion == "failure") | .id'); do
            # ジョブ名を取得
            JOB_NAME=$(echo "$JOBS" | jq -r --arg id "$job" '.[] | select(.id == ($id | tonumber)) | .name')
            echo "失敗したジョブ: $JOB_NAME" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            
            # エラーの部分だけを取得（最大20行）
            echo "エラー内容:" >> $GITHUB_ENV
            gh api repos/${{ github.repository }}/actions/jobs/${job}/logs 2>&1 | \
              grep -B 2 -A 5 -i "error\|fail\|Found multiple\|Expected\|Received" | \
              head -30 >> $GITHUB_ENV || echo "ログを取得できませんでした" >> $GITHUB_ENV
            
            echo "" >> $GITHUB_ENV
            echo "---" >> $GITHUB_ENV
          done

          echo "EOF" >> $GITHUB_ENV

      - name: Run AI check
        id: ai-check
        uses: actions/ai-inference@v1
        with:
          model: "openai/gpt-4o"
          prompt: |
            あなたは、GitHub ActionsとJavaScript/TypeScriptのテストのプロです。初心者でも理解できるように
            以下の形式で簡潔に（全体で10行以内）説明してください。
            エラーの内容は以下です。

            **失敗したワークフロー:**
            - ワークフロー名: ${{ env.WORKFLOW_NAME }}
            - ブランチ: ${{ env.BRANCH_NAME }}
            - コミットSHA: ${{ env.COMMIT_SHA }}
            - 使用技術: Vite, Supabase, Firebase

            **エラーログ:**
            ```
            ${{ env.FAILED_LOGS }}
            ```

            **回答形式フォーマット:**
            【原因】1-2行で説明
            【解決方法】具体的な手順を1-2個
            【予防策】1つだけ

      - name: Save AI response to summary
        if: always()
        run: |
          # GitHub Actionsのサマリーに出力（Web UIで確認可能）
          echo "## 分析結果" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.ai-check.outputs.response }}' | base64 | base64 -d >> $GITHUB_STEP_SUMMARY
